---
# tasks file for python3 - EL Family

- name: EL Family | Installing epel-release
  ansible.builtin.package:
    name: epel-release
    state: present
    update_cache: yes

- name: EL Family | Installing {{ python3_app_el_package }}
  ansible.builtin.package:
    name: "{{ python3_app_el_package }}"
    state: "{{ python3_desired_state }}"
    update_cache: yes
