---
# tasks file for python3 - CentOS

- name: Installing epel-release on EL systems
  package:
    name: epel-release
    state: present
    update_cache: yes
- name: Installing "{{ python3_app_el_package }}" on EL systems
  package:
    name: "{{ python3_app_el_package }}"
    state: "{{ python3_desired_state }}"
    update_cache: yes
