---
# tasks file for python3 - Debian

- name: Installing "{{ python3_app_debian_package }}" on Debian systems
  package:
    name: "{{ python3_app_debian_package }}"
    state: "{{ python3_desired_state }}"
    force_apt_get: yes
    update_cache: yes
